language: node_js
node_js:
- '4'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - JOBS=1
  matrix:
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
- npm install -g npm@4
- npm --version
script:
- node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
deploy:
  provider: npm
  email: lukesarge@gmail.com
  skip_cleanup: true
  api_key:
    secure: s87CFnT8hyd2YOlaIdCEGfSLyiy96oa85tqW+zb9TYfzCqik4/mIE4TwdjqU/e8gQfFwBuaUJxEdH87X3crCRqduMe595u/ZpUzPN/dEfVpIbTyluw2Qc1ALBvbZ1s9zG6txxrZ4YSOpHVQcpJwp14yRKTPw3f/jgLGVsRhwlR8PDLZ4sCSUju88DNWOHL84uebcGzZksLHslDikglCdHaMfQ3/bzAUeveY8wNjfjdatmUpLS93ug/ov5IFILWuq9F+LbT8uhRu8hwfOtFGJjTW2NBfA2B28V8bIVWlz0TlhnYCu/lwVELZVg70z7bqx5KihXMzOoNcImze/BCwcEBOb2KmAP2QCFLHMc+qdLF68aujPxdfCfmsYtw46Kk7nlqPeQxZUS55gdrUOk/5HgwVukYx2BuXOd/JU6gqH3ahto03FhJTftB7g1xtinCrYbOEJu1NhQTKuBTEbwI/LDHncoWk827I56RMkETqC7FmPauLMW7cK6sih+YOV1QymTQJANhVT3gYjfGSvZSGebszrrE8zMTUlwpNgv/sOkQPCWXwWMTIu55QLFPVQ80QPZECjY4uc6bwjWkk/VGzLzLF3B79AXGdc04WagsAfBeNbIH5+YyzI0qXxtkqiaLg8t0Djgr1nIF6VirmHq4hyTvPM1WFwQVrSlb54aDlT7sw=
  on:
    condition: "$EMBER_TRY_SCENARIO = 'ember-default'"
    tags: true
    branch: master
